export const SAVE_LIST_SERVICES = 'SAVE_LIST_CUSTOMERS'
export const SAVE_FILTER_TYPE = 'SAVE_FILTER_TYPE'
// export const SAVE_ACTION_CUSTOMER = 'SAVE_ACTION_CUSTOMER'
// export const SAVE_TYPE_ACTION = 'SAVE_TYPE_ACTION'

export default {
    SAVE_LIST_SERVICES,
    SAVE_FILTER_TYPE,
    // SAVE_ACTION_CUSTOMER,
    // SAVE_TYPE_ACTION
}
